"""changes in decimal places

Revision ID: 5477c397567a
Revises: a196c6694d3e
Create Date: 2024-04-10 15:30:28.711636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5477c397567a'
down_revision: Union[str, None] = 'a196c6694d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commodity', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=9),
               type_=sa.DECIMAL(precision=22, scale=18),
               existing_nullable=True)
    op.alter_column('transaction', 'value',
               existing_type=sa.NUMERIC(precision=16, scale=14),
               type_=sa.DECIMAL(precision=22, scale=18),
               existing_nullable=True)
    op.alter_column('transaction', 'txn_fee',
               existing_type=sa.NUMERIC(precision=16, scale=14),
               type_=sa.DECIMAL(precision=22, scale=18),
               existing_nullable=True)
    op.alter_column('wallet', 'balance',
               existing_type=sa.NUMERIC(precision=10, scale=9),
               type_=sa.DECIMAL(precision=22, scale=18),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'balance',
               existing_type=sa.DECIMAL(precision=22, scale=18),
               type_=sa.NUMERIC(precision=10, scale=9),
               existing_nullable=True)
    op.alter_column('transaction', 'txn_fee',
               existing_type=sa.DECIMAL(precision=22, scale=18),
               type_=sa.NUMERIC(precision=16, scale=14),
               existing_nullable=True)
    op.alter_column('transaction', 'value',
               existing_type=sa.DECIMAL(precision=22, scale=18),
               type_=sa.NUMERIC(precision=16, scale=14),
               existing_nullable=True)
    op.alter_column('commodity', 'price',
               existing_type=sa.DECIMAL(precision=22, scale=18),
               type_=sa.NUMERIC(precision=10, scale=9),
               existing_nullable=True)
    # ### end Alembic commands ###
