"""add indexes in Wallet model(user, adress)

Revision ID: 56193eb58ad0
Revises: 4a1c993b041c
Create Date: 2024-06-16 17:06:19.522821

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "56193eb58ad0"
down_revision: Union[str, None] = "4a1c993b041c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_wallet_address", "wallet", ["address"], unique=False)
    op.create_index("ix_wallet_user_id", "wallet", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wallet_user_id", table_name="wallet")
    op.drop_index("ix_wallet_address", table_name="wallet")
    # ### end Alembic commands ###
