"""add return nullable collumn in order table

Revision ID: 8fab4e39447b
Revises: 396f9ed9bcd1
Create Date: 2024-06-11 11:46:36.078826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fab4e39447b'
down_revision: Union[str, None] = '396f9ed9bcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('return_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'transaction', ['return_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'return_transaction_id')
    # ### end Alembic commands ###
