"""adding tnx_fee in wallet model

Revision ID: a196c6694d3e
Revises: b946f5cae8cc
Create Date: 2024-04-09 19:22:07.497106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a196c6694d3e'
down_revision: Union[str, None] = 'b946f5cae8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('txn_fee', sa.DECIMAL(precision=16, scale=14), nullable=True))
    op.alter_column('transaction', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=9),
               type_=sa.DECIMAL(precision=16, scale=14),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'value',
               existing_type=sa.DECIMAL(precision=16, scale=14),
               type_=sa.NUMERIC(precision=10, scale=9),
               existing_nullable=True)
    op.drop_column('transaction', 'txn_fee')
    # ### end Alembic commands ###
