"""add photo to message

Revision ID: dd56125bed4e
Revises: 27920f03ed04
Create Date: 2024-02-27 21:20:29.421878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = 'dd56125bed4e'
down_revision: Union[str, None] = '27920f03ed04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('photo', sqlalchemy_file.types.FileField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'photo')
    # ### end Alembic commands ###
